" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" =============== Pathogen Initialization ===============
" This loads all the plugins in ~/.vim/bundle
" Use tpope's pathogen plugin to manage all other plugins

" Disable the filetype recognition to be sure to run always pathogen
filetype off

" runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()


" =============== General Config ===============

" Turn on the syntax highlighting
syntax on

set encoding=utf-8
set showcmd
set showmode
set backspace=indent,eol,start
set history=1000
set undolevels=1000
set number
set shortmess=atI
set autochdir
set autoread
set cursorline
set hidden
set t_Co=16

colorscheme solarized
set background=dark

" Lower a little bit the timeout
set timeoutlen=750

" =============== Turn Off Swap Files ===============

set noswapfile
set nobackup
set nowb

" =============== Search Settings ===============

set hlsearch
set incsearch
set ignorecase
set smartcase

" =========== Disable Sound and Visual Errors ===========

set noerrorbells
set novisualbell
set vb t_vb=

" =============== Indentation ===============

set autoindent
set copyindent
set smartindent
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

set foldmethod=marker
"
"Display non visible characters, (tab, end of line and white spaces)
set list
set listchars=tab:▸\ ,eol:¬,trail:·,precedes:…,extends:…
set showbreak=↩\ 


set nowrap

" Reactivate the filetype recognition on indentation and plugins
filetype on
filetype indent on
filetype plugin on

" usefull for mapping Alt key on linux
set winaltkeys=no

" =============== Completion ===============

set wildmode=list:longest
set wildmenu
set wildignore=*.o,*.obj,*~
set wildignore+=*DS_Store*
set wildignore+=*.png,*.jpg,*.jpeg,*.gif
set wildignore+=*.mkv,*.avi

" =============== Scrolling ===============

set scrolloff=8
set sidescrolloff=7

" =============== Mouse ===============
if has('mouse')
    set mouse=a
endif


set statusline=%F%m%r%h%w\ [Format:\ %{&ff}]\ [Type:\ %Y]\ [Lines:\ %L\ @\ %p%%\ {%l;%v}]
set laststatus=2


" TODO: find a better approach with this
"       maybe anoterh location?
"
" Guard if for not load autocommand twice
if !exists('autocommands_loaded')
    let autocommands_loaded = 1

    au BufEnter * set cursorline
    au BufLeave * set nocursorline
    au BufReadPre * set nocursorline

    au BufNewFile,BufRead *.startup set ft=startup

endif


" ========================================
" General vim sanity improvements
" ========================================
"
"
" Change the mapleader from \ to ,
let mapleader=","

"make Y consistent with C and D
nnoremap Y y$

" ========================================
" RSI Prevention - keyboard remaps
" ========================================
" Certain things we do every day as programmers stress
" out our hands. For example, typing underscores and
" dashes are very common, and in position that require
" a lot of hand movement. Vim to the rescue

imap <silent> <M-k> _
imap <silent> <M-d> _
imap <silent> <M-K> -
imap <silent> <M-D> -
cnoremap <M-k> _
cnoremap <M-d> _
cnoremap <M-K> -
cnoremap <M-D> -

" ========================================
" Not use the arrow key in command line
" ========================================

cnoremap <C-j> <Down>
cnoremap <C-k> <Up>
cnoremap <C-h> <Left>
cnoremap <C-l> <Right>


" Remap ESC to a better shortcut. I've never type 'jj' anyway
imap jj <ESC>
cmap jj <c-c>

" Swap ; with : in normal mode
" nnoremap ; :
" nnoremap : ;

" Go to last edit location with ,.
nnoremap ,. '.

" =======================================
"           Split Manipulation
" =======================================
" Easy splits navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Resize splits
nnoremap <silent> + <c-w>+
nnoremap <silent> - <c-w>-
nnoremap <silent> > <c-w>>
nnoremap <silent> < <c-w><

" ============================
" Shortcuts for everyday tasks
" ============================

" Clean the last search
nmap <silent> <Leader>/ :nohlsearch<CR>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Quickly run the macro in the register q
nnoremap <Space> @q

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" Make selecting inside an HTML tag better
" TODO: maybe move this lines
vnoremap <silent> it itVkoj
vnoremap <silent> at atV

" Sudo to write
" stolen from Steve Losh
" cmap w!! w !sudo tee % >/dev/null
command! W exec 'w !sudo tee % > /dev/null' | e!

" Open the current buffer in the browser
nnoremap <F12> :exe ':silent !chromium %'<cr>


" NERDTree
let NERDTreeMinimalUI=1
let NERDTreeQuitOnOpen=1
map <C-f> :NERDTreeToggle<cr>

" delimitMate
inoremap <leader><Tab> <C-R>=delimitMate#JumpAny("\<leader><Tab>")<CR>

" ultisnips
let g:UltiSnipsEditSplit="vertical"
